import './index.css'
import { Lato } from 'next/font/google'
import {cx} from "@/panda/css";

const lato = Lato({subsets:['latin'], weight: ['100','300','400','700', '900'], variable: '--lato'});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cx(lato.variable)}>
      <body >{children}</body>
    </html>
  )
}
